version: '3.8'

services:
  superset:
    image: apache/superset
    container_name: superset
    ports:
      - "8088:8088"
    depends_on:
      - postgres
      - mysql
      - clickhouse
    environment:
      - SUPERSET_SECRET_KEY=Hy@1987921
      - SUPERSET_LOAD_EXAMPLES=no
      - SUPERSET_DATABASE_URI=postgresql://postgres:Hy@1987921@postgres:5432/superset
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
    command: >
      sh -c "
      sleep 30 && 
      superset fab create-admin --username admin --firstname Superset --lastname Admin --email huang13849@hotmail.com --password Hy@1987921 &&
      superset db upgrade &&
      superset init"
    networks:
      - superset_network

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=Hy@1987921
    ports:
      - "5432:5432"
    networks:
      - superset_network

  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Hy@1987921
    ports:
      - "3306:3306"
    networks:
      - superset_network

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    ports:
      - "8123:8123"
    environment:
      - CLICKHOUSE_USER=admin            # Set ClickHouse username
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1  # Enable default access management
      - CLICKHOUSE_PASSWORD=Hy@1987921
    networks:
      - superset_network

networks:
  superset_network:

