services:
  # superset:
  #   image: apache/superset
  #   container_name: superset
  #   ports:
  #     - "8088:8088"
  #   depends_on:
  #     - postgres-slave
  #   environment:
  #     - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
  #     - SUPERSET_LOAD_EXAMPLES=no
  #     - SUPERSET_DATABASE_URI=${SUPERSET_DATABASE_URI}
  #     - SUPERSET_HOME=/app/superset_home
  #   volumes:
  #     - ./superset:/app/superset_home 
  #   networks:
  #     - superset_network

  postgres-slave:
    image: postgres:latest
    container_name: postgres-slave
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "5432:5432"
    networks:
      - superset_network
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH = ${NEO4J_AUTH} # Format: neo4j/<password>
    ports:
      - "7474:7474" # HTTP access
      - "7687:7687" # Bolt access
    networks:
      - superset_network
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/import
      - ./neo4j/plugins:/plugins
  
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_MASTER_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./wordpress/themes:/var/www/html/wp-content/themes
      - ./wordpress/plugins:/var/www/html/wp-content/plugins
      - ./wordpress/uploads:/var/www/html/wp-content/uploads
    ports:
      - "8081:80" # Maps port 80 in the container to 8080 on the host
    networks:
      - superset_network

  # jupyter:
    # build: ./jupyter
  #   image: jupyter/tensorflow-notebook:latest  
  #   container_name: jupyter
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - ./jupyter/notebooks:/home/jovyan/work
  #   networks:
  #     - superset_network

  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus:/etc/prometheus
  #   networks:
  #     - superset_network
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'

networks:
  superset_network:
