version: '3.8'

services:
  superset:
    image: apache/superset
    container_name: superset
    ports:
      - "8088:8088"
    depends_on:
      - postgres-slave
      - clickhouse
    environment:
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
      - SUPERSET_LOAD_EXAMPLES=no
      - SUPERSET_DATABASE_URI=${SUPERSET_DATABASE_URI}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
    networks:
      - superset_network

  postgres-slave:
    image: postgres:latest
    container_name: postgres-slave
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5433:5432"
    networks:
      - superset_network
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
  

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    ports:
      - "8123:8123"
    environment:
      - CLICKHOUSE_USER=admin            # Set ClickHouse username
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1  # Enable default access management
      - CLICKHOUSE_PASSWORD=${PASSWORD}
    networks:
      - superset_network
        #volumes:
        #- ./clickhouse/clickhouse_data:/var/lib/clickhouse
        #- ./clickhouse/clickhouse_logs:/var/log/clickhouse-server
networks:
  superset_network:

