services:
  postgres-slave:
    image: postgres:latest
    container_name: postgres-slave
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "5432:5432"
    networks:
      - superset_network
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

  # neo4j:
  #   image: neo4j:latest
  #   container_name: neo4j
  #   environment:
  #     - NEO4J_AUTH = ${NEO4J_AUTH} # Format: neo4j/<password>
  #   ports:
  #     - "7474:7474" # HTTP access
  #     - "7687:7687" # Bolt access
  #   networks:
  #     - superset_network
  #   volumes:
  #     - ./neo4j/data:/data
  #     - ./neo4j/logs:/logs
  #     - ./neo4j/import:/import
  #     - ./neo4j/plugins:/plugins

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER} 
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - superset_network

  # wordpress_pcb:
  #   image: wordpress:latest
  #   container_name: wordpress_pcb
  #   restart: unless-stopped
  #   environment:
  #     WORDPRESS_DB_HOST: mysql
  #     WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
  #     WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
  #     WORDPRESS_DB_NAME: ${WORDPRESS_DATABASE_PCB}
  #   ports:
  #     - "8081:80"
  #   volumes:
  #     - ./wordpress/site_pcb/themes:/var/www/html/wp-content/themes
  #     - ./wordpress/site_pcb/plugins:/var/www/html/wp-content/plugins
  #     - ./wordpress/site_pcb/uploads:/var/www/html/wp-content/uploads
  #   networks:
  #     - superset_network

  # wordpress_arts:
  #   image: wordpress:latest
  #   container_name: wordpress_arts
  #   restart: unless-stopped
  #   environment:
  #     WORDPRESS_DB_HOST: mysql
  #     WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
  #     WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
  #     WORDPRESS_DB_NAME: ${WORDPRESS_DATABASE_ARTS}
  #   ports:
  #     - "8082:80"
  #   volumes:
  #     - ./wordpress/site_arts/themes:/var/www/html/wp-content/themes
  #     - ./wordpress/site_arts/plugins:/var/www/html/wp-content/plugins
  #     - ./wordpress/site_arts/uploads:/var/www/html/wp-content/uploads
  #   networks:
  #     - superset_network


networks:
  superset_network:

  # jupyter:
    # build: ./jupyter
  #   image: jupyter/tensorflow-notebook:latest  
  #   container_name: jupyter
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - ./jupyter/notebooks:/home/jovyan/work
  #   networks:
  #     - superset_network

  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus:/etc/prometheus
  #   networks:
  #     - superset_network
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'

  # superset:
  #   image: apache/superset
  #   container_name: superset
  #   ports:
  #     - "8088:8088"
  #   depends_on:
  #     - postgres-slave
  #   environment:
  #     - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
  #     - SUPERSET_LOAD_EXAMPLES=no
  #     - SUPERSET_DATABASE_URI=${SUPERSET_DATABASE_URI}
  #     - SUPERSET_HOME=/app/superset_home
  #   volumes:
  #     - ./superset:/app/superset_home 
  #   networks:
  #     - superset_network